import { NextResponse } from 'next/server';

// Define the type for your product object
interface Product {
  id: number | string;
  image: string;
  title: string;
  description: string;
  department: string;
  price: string;
  discountedPrice: string;
  colors: string[];
}

const products: Product[] = [
  {
    id: 1,
    image: '/images/best-1.png',
    title: 'Brown Jacket',
    description: 'A stylish brown jacket for a casual look.',
    department: "Men's Outerwear",
    price: '49.99',
    discountedPrice: '39.99',
    colors: ['bg-blue-500', 'bg-green-500', 'bg-orange-500', 'bg-black'],
  },
  {
    id: 2,
    image: '/images/best-2.png',
    title: 'Grey Sweater',
    description: 'A stylish grey sweater for a casual look.',
    department: "Women's Knitwear",
    price: '35.00',
    discountedPrice: '25.00',
    colors: ['bg-blue-500', 'bg-green-500', 'bg-orange-500', 'bg-black'],
  },
  
{
  id: 3,
  image: '/images/best-3.png',
  title: 'Yellow Cardigan',
  description: 'A stylish yellow cardigan for a casual look',
  department: "Women's Clothing",
  price: '45.00',
  discountedPrice: '30.00',
  colors: ['bg-blue-500', 'bg-green-500', 'bg-orange-500', 'bg-black'],
},
{
  id: 4,
  image: '/images/best-4.png',
  title: 'Yellow Floral Shirt',
  description: 'A stylish yellow floral shirt for a casual look.',
  department: "Men's Casual Wear",
  price: '25.00',
  discountedPrice: '15.00',
  colors: ['bg-blue-500', 'bg-green-500', 'bg-orange-500', 'bg-black'],
},
{
  id: 5,
  image: '/images/best-5.png',
  title: 'Light Gray Jacket',
  description: 'A stylish light gray jacket for a casual look.',
  department: "Men's Outerwear",
  price: '65.00',
  discountedPrice: '50.00',
  colors: ['bg-blue-500', 'bg-green-500', 'bg-orange-500', 'bg-black'],
},
{
  id: 6,
  image: '/images/best-6.png',
  title: 'Yellow Vest',
  description: 'A stylish yellow vest for a casual look.',
  department: "Men's Winter Wear",
  price: '35.00',
  discountedPrice: '25.00',
  colors: ['bg-blue-500', 'bg-green-500', 'bg-orange-500', 'bg-black'],
},
{
  id: 7,
  image: '/images/best-7.png',
  title: 'Printed Shirt',
  description: 'A stylish printed shirt for a casual look.',
  department: "Men's Casual Wear",
  price: '30.00',
  discountedPrice: '20.00',
  colors: ['bg-blue-500', 'bg-green-500', 'bg-orange-500', 'bg-black'],
},
{
  id: 8,
  image: '/images/best-8.png',
  title: 'Pink Sweater',
  description: 'A stylish pink sweater for a casual look.',
  department: "Women's Knitwear",
  price: '40.00',
  discountedPrice: '28.00',
  colors: ['bg-blue-500', 'bg-green-500', 'bg-orange-500', 'bg-black'],
},
{
  id: 9,
  image: '/images/best-9.png',
  title: 'Green Hoodie',
  description: 'A stylish green hoodie for a casual look.',
  department: "Men's Activewear",
  price: '50.00',
  discountedPrice: '35.00',
  colors: ['bg-blue-500', 'bg-green-500', 'bg-orange-500', 'bg-black'],
},
{
  id: 10,
  image: '/images/best-10.png',
  description: 'A stylish black hoodie for a casual look.', 
  title: 'Black Hoodie',
  department: "Men's Activewear",
  price: '55.00',
  discountedPrice: '40.00',
  colors: ['bg-blue-500', 'bg-green-500', 'bg-orange-500', 'bg-black'],
},
{
  id: 11,
  image: '/images/best-11.png',
  description : 'A stylish blue printed shirt for a casual look.',
  title: 'Blue Printed Shirt',
  department: "Men's Casual Wear",
  price: '30.00',
  discountedPrice: '20.00',
  colors: ['bg-blue-500', 'bg-green-500', 'bg-orange-500', 'bg-black'],
},
{
  id: 12,
  image: '/images/best-12.png',
  title: 'Brown Leather Jacket',
  description: 'A stylish brown leather jacket for a rugged look.',
  department: "Women's Outerwear",
  price: '80.00',
  discountedPrice: '65.00',
  colors: ['bg-blue-500', 'bg-green-500', 'bg-orange-500', 'bg-black'],
},
{
    id: '13',
    title: 'Trendy Part Wear',
    description : 'A stylish outfit perfect for trendy party events.',
    department: "Party Wear",
    price: '20.99',
    discountedPrice: '10.99',
    image: '/images/party-1.png',
    colors: ['bg-blue-500', 'bg-green-500'],
  },
  {
    id: '14',
    title: 'White Elegant Outfit',
    description: 'A sleek and elegant white outfit for any formal occasion.',
    department: "Party Wear",
    price: '21.99',
    discountedPrice: '11.99',
    image: '/images/party-2.png',
    colors: ['bg-blue-500', 'bg-green-500'],
  },
  {
    id: '15',
    title: 'Black Short Frock',
    description: 'A trendy black short frock with a stylish flair',
    department: "Party Wear",
    price: '22.99',
    discountedPrice: '12.99',
    image: '/images/party-3.png',
    colors: ['bg-blue-500', 'bg-green-500'],
  },
  {
    id: '16',
    title: 'Classy Gown',
    description: 'A luxurious and classy gown perfect for upscale events.',
    department: "Party Wear",
    price: '23.99',
    discountedPrice: '13.99',
    image: '/images/party-4.png',
    colors: ['bg-blue-500', 'bg-green-500'],
  },
  {
    id: '17',
    title: 'Fashionable Party Wear',
    description: 'Fashion-forward outfit ideal for fashionable party occasions.',
    department: "Party Wear",
    price: '24.99',
    discountedPrice: '14.99',
    image: '/images/party-5.png',
    colors: ['bg-blue-500', 'bg-green-500'],
  },
  {
    id: '18',
    title: 'Black Snazzy Outfit',
    description: 'A snazzy black outfit that adds a bold touch to your look',
    department: "Party Wear",
    price: '25.99',
    discountedPrice: '15.99',
    image: '/images/party-6.png',
    colors: ['bg-blue-500', 'bg-green-500'],
  },
  {
    id: '19',
    title: 'Glamorous Outfit',
    description: 'A stunning and glamorous outfit that shines at parties.',
    department: "Party Wear",
    price: '26.99',
    discountedPrice: '16.99',
    image: '/images/party-7.png',
    colors: ['bg-blue-500', 'bg-green-500'],
  },
  {
    id: '20',
    title: 'Dapper Cocktail Dress',
    description: 'A sophisticated cocktail dress for chic gatherings',
    department: "Party Wear",
    price: '27.99',
    discountedPrice: '17.99',
    image: '/images/party-8.png',
    colors: ['bg-blue-500', 'bg-green-500'],
  },
  
  // Casual
  {
    id: '21',
    title: 'Sleek Casual Outfit',
    description: 'A sleek and fashionable outfit for laid-back occasions.',
    department: "Casual",
    price: '15.99',
    discountedPrice: '8.99',
    image: '/images/casual-1.png',
    colors: ['bg-orange-500', 'bg-black'],
  },
  {
    id: '22',
    title: 'loungewear set',
    description: 'A comfortable loungewear set perfect for casual days',
    department: "Casual",
    price: '16.99',
    discountedPrice: '9.99',
    image: '/images/casual-2.png',
    colors: ['bg-orange-500', 'bg-black'],
  },
  {
    id: '23',
    title: 'Stylish Outfit',
    description: 'A chic, stylish outfit that’s perfect for everyday wear.',
    department: "Casual",
    price: '17.99',
    discountedPrice: '10.99',
    image: '/images/casual-3.png',
    colors: ['bg-orange-500', 'bg-black'],
  },
  {
    id: '24',
    title: 'Smart Casual Dress',
    description: 'A smart dress that strikes the perfect balance between casual and formal.',
    department: "Casual",
    price: '18.99',
    discountedPrice: '11.99',
    image: '/images/casual-4.png',
    colors: ['bg-orange-500', 'bg-black'],
  },
  {
    id: '25',
    title: 'Comfy T-Shirt',
    description: 'A classic and comfy t-shirt for casual days.',
    department: "Casual",
    price: '19.99',
    discountedPrice: '12.99',
    image: '/images/casual-5.png',
    colors: ['bg-orange-500', 'bg-black'],
  },
  {
    id: '26',
    title: 'Black Versatile Outfit',
    description: 'A versatile black outfit that suits various casual settings.',
    department: "Casual",
    price: '20.99',
    discountedPrice: '13.99',
    image: '/images/casual-6.png',
    colors: ['bg-orange-500', 'bg-black'],
  },
  {
    id: '27',
    title: 'Pink Easygoing Outfit',
    description: 'A soft and casual pink outfit for a relaxed day.',
    department: "Casual",
    price: '21.99',
    discountedPrice: '14.99',
    image: '/images/casual-7.png',
    colors: ['bg-orange-500', 'bg-black'],
  },
  {
    id: '28',
    title: 'Cozy Floral Frock',
    description: 'A cozy floral dress that blends style and comfort.',
    department: "Casual",
    price: '22.99',
    discountedPrice: '15.99',
    image: '/images/casual-8.png',
    colors: ['bg-orange-500', 'bg-black'],
  },

  // Formal
  {
    id: '29',
    title: 'Sleek Black Dress',
    description: 'A sleek black dress for an elegant formal look.',
    department: "Formal",
    price: '50.99',
    discountedPrice: '25.99',
    image: '/images/formal-1.png',
    colors: ['bg-purple-500', 'bg-yellow-500'],
  },
  {
    id: '30',
    title: 'Chic Dress',
    description: 'A chic and fashionable dress perfect for formal events.',
    department: "Formal",
    price: '51.99',
    discountedPrice: '26.99',
    image: '/images/formal-2.png',
    colors: ['bg-purple-500', 'bg-yellow-500'],
  },
  {
    id: '31',
    title: 'Tailored Outfit',
    description: 'A perfectly tailored outfit for a polished look.',
    department: "Formal",
    price: '52.99',
    discountedPrice: '27.99',
    image: '/images/formal-3.png',
    colors: ['bg-purple-500', 'bg-yellow-500'],
  },
  {
    id: '32',
    title: 'Black Debonair Outfit',
    description: 'A sophisticated and debonair black outfit for formal occasions.',
    department: "Formal",
    price: '53.99',
    discountedPrice: '28.99',
    image: '/images/formal-4.png',
    colors: ['bg-purple-500', 'bg-yellow-500'],
  },
  {
    id: '33',
    title: 'Immaculate Dress',
    description: 'n immaculate dress for a flawless formal look.',
    department: "Formal",
    price: '54.99',
    discountedPrice: '29.99',
    image: '/images/formal-5.png',
    colors: ['bg-purple-500', 'bg-yellow-500'],
  },
  {
    id: '34',
    title: 'Black Opulent Outfit',
    description: 'An opulent black outfit for a luxurious appearance.',
    department: "Formal",
    price: '55.99',
    discountedPrice: '30.99',
    image: '/images/formal-6.png',
    colors: ['bg-purple-500', 'bg-yellow-500'],
  },
  {
    id: '35',
    title: 'Elegant Dress Pant',
    description: 'Elegant dress pants for a sharp and professional appearance.',
    department: "Formal",
    price: '56.99',
    discountedPrice: '31.99',
    image: '/images/formal-7.png',
    colors: ['bg-purple-500', 'bg-yellow-500'],
  },
  {
    id: '36',
    title: 'Graceful Outfit',
    description: 'A graceful formal outfit that exudes sophistication.',
    department: "Formal",
    price: '57.99',
    discountedPrice: '32.99',
    image: '/images/formal-8.png',
    colors: ['bg-purple-500', 'bg-yellow-500'],
  },

  // Summer
  {
    id: '37',
    title: 'Soft Frock',
    description: 'A lightweight frock perfect for warm summer days.',
    department: "Summer",
    price: '30.99',
    discountedPrice: '20.99',
    image: '/images/summer-1.png',
    colors: ['bg-red-500', 'bg-pink-500'],
  },
  {
    id: '38',
    title: 'Floral Gown',
    description: 'A flowy floral gown ideal for sunny occasions.',
    department: "Summer",
    price: '31.99',
    discountedPrice: '21.99',
    image: '/images/summer-2.png',
    colors: ['bg-red-500', 'bg-pink-500'],
  },
  {
    id: '39',
    title: 'Chill Printed Shirt',
    description: 'A cool and vibrant printed shirt for a relaxed summer vibe',
    department: "Summer",
    price: '32.99',
    discountedPrice: '22.99',
    image: '/images/summer-3.png',
    colors: ['bg-red-500', 'bg-pink-500'],
  },
  {
    id: '40',
    title: 'Sleek T-shirt',
    description: 'A sleek and stylish t-shirt for casual summer outings.',
    department: "Summer",
    price: '33.99',
    discountedPrice: '23.99',
    image: '/images/summer-4.png',
    colors: ['bg-red-500', 'bg-pink-500'],
  },
  {
    id: '41',
    title: 'Comfortable Romper',
    description: 'A comfy romper for effortless summer style.',
    department: "Summer",
    price: '34.99',
    discountedPrice: '24.99',
    image: '/images/summer-5.png',
    colors: ['bg-red-500', 'bg-pink-500'],
  },
  {
    id: '42',
    title: 'Breezy T-shirt',
    description: 'A breezy t-shirt designed for maximum comfort in the heat.',
    department: "Summer",
    price: '35.99',
    discountedPrice: '25.99',
    image: '/images/summer-6.png',
    colors: ['bg-red-500', 'bg-pink-500'],
  },
  {
    id: '43',
    title: 'Classy Romper',
    description: 'A classy romper that combines elegance and comfort.',
    department: "Summer",
    price: '36.99',
    discountedPrice: '26.99',
    image: '/images/summer-7.png',
    colors: ['bg-red-500', 'bg-pink-500'],
  },
  {
    id: '44',
    title: 'Black Romper',
    description: 'A trendy black romper that’s perfect for summer evenings.',
    department: "Summer",
    price: '37.99',
    discountedPrice: '27.99',
    image: '/images/summer-8.png',
    colors: ['bg-red-500', 'bg-pink-500'],
  },

  // Winter
  {
    id: '45',
    title: 'Luxe Winter Outfit',
    description: 'A luxurious outfit perfect for winter occasions.',
    department: "Winter",
    price: '80.99',
    discountedPrice: '50.99',
    image: '/images/winter-1.png',
    colors: ['bg-gray-500', 'bg-teal-500'],
  },
  {
    id: '46',
    title: 'Sporty Jacket',
    description: 'A sporty jacket to keep you stylish and warm in the winter.',
    department: "Winter",
    price: '81.99',
    discountedPrice: '51.99',
    image: '/images/winter-2.png',
    colors: ['bg-gray-500', 'bg-teal-500'],
  },
  {
    id: '47',
    title: 'Classy Korean Coat',
    description: 'A chic Korean-style coat to keep you fashionable in winter.',
    department: "Winter",
    price: '82.99',
    discountedPrice: '52.99',
    image: '/images/winter-3.png',
    colors: ['bg-gray-500', 'bg-teal-500'],
  },
  {
    id: '48',
    title: 'Grey Trendy Sweater',
    description: 'A trendy grey sweater to keep you warm and fashionable.',
    department: "Winter",
    price: '83.99',
    discountedPrice: '53.99',
    image: '/images/winter-4.png',
    colors: ['bg-gray-500', 'bg-teal-500'],
  },
  {
    id: '49',
    title: 'Classy Sweater',
    description: 'A classy and cozy sweater ideal for chilly days.',
    department: "Winter",
    price: '84.99',
    discountedPrice: '54.99',
    image: '/images/winter-5.png',
    colors: ['bg-gray-500', 'bg-teal-500'],
  },
  {
    id: '50',
    title: 'White Zipper Hoodie',
    description: 'A comfortable and stylish white hoodie with a zipper.',
    department: "Winter",
    price: '85.99',
    discountedPrice: '55.99',
    image: '/images/winter-6.png',
    colors: ['bg-gray-500', 'bg-teal-500'],
  },
  {
    id: '51',
    title: 'Blue Simple Hoodie',
    description: 'A simple and comfortable blue hoodie for everyday wear.',
    department: "Winter",
    price: '86.99',
    discountedPrice: '56.99',
    image: '/images/winter-7.png',
    colors: ['bg-gray-500', 'bg-teal-500'],
  },
  {
    id: '52',
    title: 'Lavender Printed Hoodie',
    description: 'A vibrant lavender hoodie with a stylish print.',
    department: "Winter",
    price: '87.99',
    discountedPrice: '57.99',
    image: '/images/winter-8.png',
    colors: ['bg-gray-500', 'bg-teal-500'],
  },

];

// Example API route
export async function GET() {
  try {
    // If you need to catch a possible error and handle it
    throw new Error("Sample error"); // Example error for demonstration

    // Normally, you can process and return the response
    return NextResponse.json(products);
  } catch (error: unknown) {
    // Type assertion to narrow the error type
    if (error instanceof Error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }
    // If the error is not an instance of Error
    return NextResponse.json({ error: 'An unknown error occurred' }, { status: 500 });
  }
}
